#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xf2e95bb9, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x19c3f856, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x73ed3ebe, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x8022511, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x8733c9e1, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xd7c25e4f, __VMLINUX_SYMBOL_STR(new_sync_write) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x9636927d, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0xb6467197, __VMLINUX_SYMBOL_STR(sb_min_blocksize) },
	{ 0x54342b3e, __VMLINUX_SYMBOL_STR(generic_getxattr) },
	{ 0x1ffc24d8, __VMLINUX_SYMBOL_STR(__bread) },
	{ 0x55ff0f3f, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xa99ea6f6, __VMLINUX_SYMBOL_STR(bio_alloc_bioset) },
	{ 0xb7d043a6, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x8d232ade, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x9d135407, __VMLINUX_SYMBOL_STR(filemap_write_and_wait_range) },
	{ 0x27f15ec9, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xc2f1aea9, __VMLINUX_SYMBOL_STR(blkdev_issue_flush) },
	{ 0xacf4d843, __VMLINUX_SYMBOL_STR(match_strdup) },
	{ 0x3e178701, __VMLINUX_SYMBOL_STR(filemap_write_and_wait) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x563380f1, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x91831d70, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xa2da3e6f, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0x4be085e0, __VMLINUX_SYMBOL_STR(block_read_full_page) },
	{ 0x3f2a0f29, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xe391a8e5, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x6767bd9, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x50f262c, __VMLINUX_SYMBOL_STR(page_symlink_inode_operations) },
	{ 0xce5cb856, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0xb0e429ec, __VMLINUX_SYMBOL_STR(igrab) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x27f7ddbd, __VMLINUX_SYMBOL_STR(generic_setxattr) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x307c2fd0, __VMLINUX_SYMBOL_STR(generic_check_addressable) },
	{ 0xf165970d, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x7598f3b7, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x16a2a1ba, __VMLINUX_SYMBOL_STR(from_kgid_munged) },
	{ 0x28124e6f, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xec730387, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcdddc9ec, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x6d0aba34, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x373f6076, __VMLINUX_SYMBOL_STR(inode_owner_or_capable) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xdaf23bd8, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x61870078, __VMLINUX_SYMBOL_STR(inode_add_bytes) },
	{ 0xac7a6185, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x64cb4378, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x5b6d8625, __VMLINUX_SYMBOL_STR(d_rehash) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x14d225e7, __VMLINUX_SYMBOL_STR(bio_add_page) },
	{ 0x7c1372e8, __VMLINUX_SYMBOL_STR(panic) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xc1f2e51b, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x4096bf3b, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0xcfa47fb, __VMLINUX_SYMBOL_STR(security_inode_init_security) },
	{ 0xcfdfb0c2, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x96d1bf40, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3dab137a, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0xf4b2654d, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x68aca4ad, __VMLINUX_SYMBOL_STR(down) },
	{ 0x7a3a4526, __VMLINUX_SYMBOL_STR(page_symlink) },
	{ 0x72062b7a, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0xf9d767cf, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x8524a7ed, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0xf76cd1ca, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xa5705263, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x209c204b, __VMLINUX_SYMBOL_STR(mark_page_accessed) },
	{ 0xd51fa845, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x8a98cf12, __VMLINUX_SYMBOL_STR(mnt_drop_write_file) },
	{ 0xde9f7ad9, __VMLINUX_SYMBOL_STR(submit_bio) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x10031e40, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xea77a34a, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0xead8fa91, __VMLINUX_SYMBOL_STR(pagecache_write_end) },
	{ 0x350d27c5, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0xdaf2fd26, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x105d8a4c, __VMLINUX_SYMBOL_STR(try_to_free_buffers) },
	{ 0xb2c8e7bb, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0xeeec26a7, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x48679bf, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0x1c7e6713, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xcaf67738, __VMLINUX_SYMBOL_STR(mnt_want_write_file) },
	{ 0x9d573e8f, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0x5e95b1cd, __VMLINUX_SYMBOL_STR(current_umask) },
	{ 0xaf7f4b7e, __VMLINUX_SYMBOL_STR(inode_set_bytes) },
	{ 0xe57b676b, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x20705009, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x35965ab1, __VMLINUX_SYMBOL_STR(sync_inode_metadata) },
	{ 0x45ec2f4b, __VMLINUX_SYMBOL_STR(new_sync_read) },
	{ 0x41814cb8, __VMLINUX_SYMBOL_STR(dirty_writeback_interval) },
	{ 0x7635873, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xf5a3b32c, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xbb720cc4, __VMLINUX_SYMBOL_STR(generic_file_write_iter) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x8a21e9a7, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x39dbd525, __VMLINUX_SYMBOL_STR(cont_write_begin) },
	{ 0xaadf6cae, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x7f020a44, __VMLINUX_SYMBOL_STR(inode_dio_wait) },
	{ 0x9cd8ae07, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x24467ab4, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0x71e3cecb, __VMLINUX_SYMBOL_STR(up) },
	{ 0x76b55542, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x243931fe, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x3e57dee6, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x58534bf3, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x434773ab, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0x9cc0694a, __VMLINUX_SYMBOL_STR(ioctl_by_bdev) },
	{ 0xa507e420, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xdd8324b8, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xaedcdaf9, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x56390581, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x8bfdbead, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0xe9b8c32c, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0xcad100fe, __VMLINUX_SYMBOL_STR(pagecache_write_begin) },
	{ 0x34da2a2a, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0xd08b5a16, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0xffe6ff1f, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x53cddc7f, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

